### PR TITLE
get-market should also print current market authority

### PR DESCRIPTION
**Pull request by eugene-chen**

### CODE REVIEW

**Review by jarry-xiao — APPROVED** [review]

**Comment by throwbackjams** [comment]
I may be hallucinating but isn't this already in master? L129 in print_helpers.rs

**Comment by eugene-chen** [comment]
@throwbackjams I don't see it?

**Comment by throwbackjams** [comment]
@eugene-chen Hm weird - did you pull master? I see it here https://github.com/Ellipsis-Labs/phoenix-cli/blob/beeea310836510e4ffb9850fe4c91c9ef0f8bd3e/src/lib/helpers/print_helpers.rs#L129

Taker fee print is there as well a few lines down

**Comment by throwbackjams** [comment]
Uncollected and collected fees are not printed in the master though and are additive so will approve since it looks like there's no conflict

**Review by throwbackjams — APPROVED** [review]

**Comment by throwbackjams** [comment]
Uncollected and collected fees are not currently being printed in master though and are additive; also looks like there are no conflicts so I approved

**Comment by eugene-chen** [comment]
ah thanks I see. i removed the line i added

**Pull request merged**
